### ISSUE TITLE
BowerにあるCSSもwebpackでまとめたい

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#16]
@hrl7 さん
でも bower_componentsのcssファイルをjsに変換してwebpackするのにはちょっと違和感が・・
CSSはCSSでまとめて、CSSとして出力できませんか・・

**Comment by zigen** [comment]
jsに埋め込んでしまう事で, HTMLにわざわざ書く量が減るし, 
ページごとにbundle.jsを生成したりすると, 一体化できるという点では, requre('./hoge.css')するのは悪くないかと思います。
新しいページをつくったときに, それ用のhoge.bundle.jsとhoge.cssをHTMLにいちいち書き込むより, `<script src ="hoge.bundle.js"><script>`だけで済むなら, そっちの方がよいです。

もちろん, ページに依存しない単位でjsとcssを生成するのであれば, 個別にcssを生成するのも一つの手ですかね。
もしそうであれば, 以下の方法でどうにかなるかと思います。
https://webpack.github.io/docs/stylesheets.html#separate-css-bundle

**Comment by shundroid** [comment]
わかりました！
JSに埋め込んでもいいと思ったので、それでやりたいと思います。

**Comment by shundroid** [comment]
Babibubebonさん、すみません。Assignee間違えました。

**Comment by shundroid** [comment]
#43 プルリク投げました。
