### ISSUE TITLE
【Webpack】babel-loader -> es6-loader

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#17]
UglifyJsPluginで、アロー関数を使っているとエラーが出ているため、
babel-loaderを使っている。
しかし、重い。
ess6-loader にしたいが、次のようなエラーが出てしまう。

```
ERROR in Cannot convert a Symbol value to a string
```

**Comment by zigen** [comment]
babel-loaderってそんなに重いですかね？
手元でまわしてみたら1.63secだったので, 充分な速度だと思いますが。。。

**Comment by shundroid** [comment]
Troubleshooting
babel-loader is slow!

Make sure you are transforming as few files as possible. Because you are probably matching /.js$/, you might be transforming the node_modules folder or other unwanted source.

To exclude node_modules, see the exclude option in the loaders config as documented above.

You can also speed up babel-loader by as much as 2x by using the cacheDirectory option. This will cache transformations to the filesystem.

https://github.com/babel/babel-loader#babel-loader-is-slow

と書いてあります。遅いらしいです。

**Comment by zigen** [comment]
書いてあるようにcacheDirectoryやってみたら早くなりませんかねー？

**Comment by shundroid** [comment]
すみません、見のがしていました・・
やってみます。
時間的に、試すのは明日になるそうです。よろしくお願いします。

**Comment by zigen** [comment]
やってみたらすごい早くなりましたー
1.5secくらいだったのが0.6secくらいまでになった。。。

**Comment by zigen** [comment]
@shundroid もうmasterにmergeしたので, 手元で試してみてください！
https://github.com/comozilla/Parapara-Canvas-Editor/pull/30

**Comment by shundroid** [comment]
@hrl7 さん、やってくださり、ありがとうございます！試してみます。

**Comment by shundroid** [comment]
やってみた結果、0.03秒くらいです！
本当にありがとうございます！
Issueは閉じてしまっても良いですかね

**Comment by shundroid** [comment]
milestoneがあり、完了したとなるので、閉じさせていただきます！
