### ISSUE TITLE
Webpack-dev-server livereloadだとCanvasに描けられない

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#18]
http://localhost:8080/webpack-dev-server/index.html
にアクセスしても、Canvasに描けないです。

http://localhost:8080/
だと、livereloadしませんが、描けます。

**Comment by zigen** [comment]
loadのタイミングの問題っぽいな。
canvas.widthとheightを取得するのが早すぎるのかな

**Comment by zigen** [comment]
webpack-dev-serverに配布させるのが悪いのもありそうだな

**Comment by shundroid** [comment]
そうですね・・。
これで loadのタイミングを変えるのもなんというか・・
browsersyncとか、選択肢はありますが、どうしますか。
また、webpack-dev-server にも、iframeとは別のインラインモードがあるそうです。
https://webpack.github.io/docs/webpack-dev-server.html

**Comment by zigen** [comment]
今後のモバイル対応などを考えると, 早めにbrowser-syncを使っておくのは悪くない手ですね

**Comment by shundroid** [comment]
そうですねー。
では早速やります。
