### ISSUE TITLE
buildスクリプトの追加

### ISSUE THREAD

**Issue by zigen** [comozilla/Parapara-Canvas-Editor#3]
webpackでbuildしたとき, production用のbundle.min.jsみたいなのがあると便利。

**Comment by shundroid** [comment]
ありがとうございます！！
たしかに！
gulp でtask作ってやるのがいいですかね

**Comment by zigen** [comment]
npmのpackage.jsonにscriptsで入れておくといいんじゃないかな？
globalでgulpとかいれたくないし。
基本的にwebpack.config.jsにいろいろ書いて, `npm run build` とかできると嬉しいかな。
[このへんあたりを参考に](http://qiita.com/Jxck_/items/efaff21b977ddc782971)

**Comment by shundroid** [comment]
ありがとうございました！！
npm run って便利ですね。
仰るとおり、実際の処理を webpack.config.js に入れて、
それを package.json で呼び出せるように書くのがいいと思いました。

**Comment by shundroid** [comment]
https://webpack.github.io/docs/usage-with-gulp.html
ここを見てやっていきます

**Comment by shundroid** [comment]
@hrl7 さん

Gulpでやる際、gulp-webpackを使うか、webpack単体で使うかの２パターンが有り、
以下の様なメリット・デメリットが有ります。
今回は gulp-webpack を使っていきたいです。
しかし、これだと webpack-dev-server が使えないっぽいので、
browsersync を使うかもです。
OKでしょうか。

### gulp-webpack

#### メリット:
- uglify できる
- コードはgulp.src などで書け、gulpらしい書き方

#### デメリット:
- webpack-dev-server できない。
  - browsersync
  - webpack-dev-server の iFrameだと書けない問題もある

### webpack

#### メリット:
- 公式のサイトのやり方。 https://webpack.github.io/docs/usage-with-gulp.html
- webpack-dev-serverが使える

#### デメリット:
- uglifyできない。
- gulp を使った良さが活かせられない
- dev-server 使用時と通常時の切り替えを引数（minimist）でやろうとしたが、できない。
  - タスクをそれぞれで作る必要がある

**Comment by zigen** [comment]
@shundroid 
どちらでもよいと思う。
個人的には, gulpをあまり書きたくない。

webpackはoptimizeの設定するとuglifyみたいなこととかもっといろいろできる。
http://webpack.github.io/docs/optimization.html

browser-sync と webpack-dev-serverをまとめるやり方もあるにはある

**Comment by shundroid** [comment]
@hrl7 さん
ご返信有り難うございます。
あと10分ほどでプルリクが多分出せるので、
少々お待ち下さい。
Gulp は結局 webpack を直で使うようにしました。
Uglifyもできたし、シンプルに仕上がったからです。

> 個人的には, gulpをあまり書きたくない。

そうですか。今、Gulpで min、dev-server モードをわけられるようにしました。
Webpack.config.js でも、モードチェンジっぽいのはできますでしょうか。
一応、プルリクすぐ投げるので、少々お待ち下さい。

**Comment by zigen** [comment]
まぁ, gulpとかgruntとかそういうのは, 趣味というか宗教みたいなものだし, 
動くものがあれば, 俺はそれを使うだけなので, あまり気にしていないです。

**Comment by shundroid** [comment]
わかりました！
プルリク少々お待ち下さい。
