### ISSUE TITLE
ColorPicker.addColorUIという名前を修正しよう

### ISSUE THREAD

**Issue by zigen** [comozilla/Parapara-Canvas-Editor#35]
addColorUIだと, ちょっと英語として意味が分かりづらく, 誤解を生み易いと考えられます。
UIを追加するのだとすると, 色のデータは別に追加する必要があるのかなって考えてしまうと思います。
UI(HTMLElement)を生成しながら, 色のデータも追加するのだとすると, 
addColorやaddPaletteといった名前がいいんじゃないかと思います。

**Comment by shundroid** [comment]
ありがとうございます。

> UIを追加するのだとすると, 色のデータは別に追加する必要があるのかなって考えてしまうと思います。

たしかにそうです。気づきませんでした。
`addPalette`で行こうと思います。
