### ISSUE TITLE
ModelとViewを分割する

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#50]
- テストケースが作りやすくなる
- CanvasをリサイズしてもOKになる（描画した内容をModelにするなら） #45 
- 保存とか元に戻すとかもできるようになる
- そうするとFrameでCanvasをたくさん作るより、1つのCanvasでFrameの内容となるModelを切り替えたほうが良くなる

**Comment by zigen** [comment]
ここにおけるModelとはなにか, Viewとはなにかをきっちり決めた方がいいような気がします。

元に戻す, とかはコマンドパターンにした方がやりやすそうですね。
https://ja.wikipedia.org/wiki/Command_%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3

**Comment by shundroid** [comment]
@hrl7 さん
Model : UIで設定できる内容（ColorPicker、LineWidthPicker、Frame）を、オブジェクトなどとして保存するもの
View : UI。

という感じで思っていました。

Command パターン使ってみたいです！
ここでは、Command という新しいクラスを作って、prototypeでundo メソッドなどを追加する感じでしょうか。
