### ISSUE TITLE
Issue/PUll Request 用のテンプレ作成

### ISSUE THREAD

**Issue by yammmt** [comozilla/Parapara-Canvas-Editor#53]
GitHub では Issue/PR のテンプレが用意できると、[こちら](http://tbpgr.hatenablog.com/entry/2016/02/19/021547) で紹介されています。
それほど時間のかかるものではなさそうなので、テンプレ作って置いておくと後々楽そうです。

**Comment by yammmt** [comment]
内容としては、 Issue/PR 共に最大三行程度の概要と詳細だけで良さそうですかね？

**Comment by shundroid** [comment]
## 概要

## 詳細

## やること
- [ ] AAA

みたいな感じですかね・・
やることがあると、Todo で編集ができるので。

**Comment by shundroid** [comment]
やること、は、Issueだけでもいい感じがします

**Comment by yammmt** [comment]
つまり、 Issue に関しては例えばこんな感じでしょうか：

---

## 概要

Issue/Pull Request の形式を統一したい。

## 詳細

GitHub では、 Issue/Pull Request に対するテンプレート機能が用意されているので、
それを利用して形式を統一すると、記入する際にも見返す際にも便利だと思う。
[こちらの解説記事も参照 (日本語) ](http://tbpgr.hatenablog.com/entry/2016/02/19/021547) 。

## やること
- [ ] テンプレートの形式決め
- [ ] ISSUE_TEMPLATE の作成
- [ ] PULL_REQUEST_TEMPLATE の作成

---

優先度とか期日みたいなものがあると良いかもしれませんが、それにしても個々で基準がばらけると怖いので誰かが代表して振っていく感じすかね

**Comment by shundroid** [comment]
そんな感じですかね！

> 期日みたいなもの

こちらは、Milestone 機能があるので OK です！

> 優先度

これも Label で振れるようにしておきます

ありがとうございます。

**Comment by shundroid** [comment]
すみません、手が滑りました・・
