### ISSUE TITLE
esLint

### ISSUE THREAD

**Issue by zigen** [comozilla/Parapara-Canvas-Editor#7]
esLintいれて, 空白やインデントあたりのチェックを自動化したい

**Comment by shundroid** [comment]
これをやると、コーディング規約のチェックとかもできてしまうらしいです！

**Comment by zigen** [comment]
https://github.com/comozilla/Parapara-Canvas-Editor/tree/lint-rule
lint-rule追加用のブランチを作りましたー
とりあえず[javascript style guide](https://developer.mozilla.org/ja/docs/JavaScript_style_guide)に沿ったruleを書いていこうと思います

**Comment by shundroid** [comment]
よろしくお願いします。
