### ISSUE TITLE
SequenceEditor クラスを作成する

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#8]
Issue閉じるまでにやること
- [x] 古いFrame用のUIを消す
  - 新しく Shinera さんが作ってくださったものを最初から実装していく感じ。
  - Frame用のUIは、下のクラスとは別で実装する。
- [ ] 新しい FrameUI クラスを作成する

何かご提案がありましたら[Wiki](https://github.com/comozilla/Parapara-Canvas-Editor/wiki/%238-%E5%AE%8C%E4%BA%86%E3%81%BE%E3%81%A7%E3%81%AE%E6%B5%81%E3%82%8C)へどうぞ

**Comment by shinera** [comment]
@shundroid 
FrameのUIのクラスまで作ったのですが、FramesControllerクラスとどう連携すればいいかわからずです・・・
（フレームへのイベントリスナの動的な追加をどこに書くか等）

そちらで作ってもらう or Issueを細分化してもらうことはできますか？

**Comment by shundroid** [comment]
@shinera おはようございます。

> FrameのUIのクラスまで作ったのですが、

ありがとうございます。
UI のクラスを作っていただいた段階で、
とりあえず一度プルリクエストを、frame-dev ブランチに投げていただいてもよろしいでしょうか、
それが終わったあと、どこに追加すればいいのかなどがわかるので、
Issueを細分化していきたいと思います。Issue わかりにくくてすみませんでした。

また、プルリクエストを投げて頂く前に、少し手順がございますので、
ご確認ください。

ESLint のルールの更新などがありましたので、それらを反映させていただきます。

### comozilla リモートがあるかをチェック

```
$ git remote -v
```

このコマンドで、`origin` の他に、`comozilla` があれば、次の手順（comozilla リモートを追加）は飛ばしてください。

### comozilla リモートを追加

```
$ git remote add comozilla https://github.com/comozilla/Parapara-Canvas-Editor.git
```

### 最新の状態を持ってくる

```
$ git fetch comozilla
```

`git branch -a` で確認すると、リモートのブランチが表示されるのがわかります。

### 最新の状態と変更をマージする

```
$ git merge remotes/comozilla/master
```

ファイルの変更が競合しなければ、自動でマージされます。
競合した場合、競合したファイルを開き修正して、コミットをしてください。
これで最新の状態とマージできました（＝＞最新状態を反映出来ました）

### ESLint をする

```
$ npm run lint
```

これでエラーが出れば直します。エラーが出なくなるまで続けます。
エラーが出なくなれば、コミットをしてください。

### プルリクエスト(=PR)を投げる

push して、Github から、PRを投げてください。
ブランチですが、**frame-dev** に向けて投げてください！

ご不明な点がございましたら、slack にでも書いていただければ見ます！
すみませんが、よろしくおねがいします。

**Comment by shinera** [comment]
@shundroid 
ありがとうございます！PRしました。

**Comment by shundroid** [comment]
@shinera Issueは見通しがつくところまで細分化しました。
#55 #56 です。
