### ISSUE TITLE
React を使う

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#88]
使えそうな場所
- sequence-view `getFrameTemplate`
- side-btn の Modeを変えているところ

**Comment by zigen** [comment]
ところどころReactを使うのはあまりおすすめできない。
やるなら, ある程度まとまった範囲に適用しないと, 管理がしづらい。
今後さらにメニューやらパネルやら, 複雑なUIが増えていくのであれば, 
ViewをReactに任せるのはありだとおもう

もし局所的にやるのであれば, Vue.jsあたりをおすすめしておく。
https://jp.vuejs.org/

**Comment by shundroid** [comment]
@hrl7 
Vue.js ですか。使ったことないな。
試してみたいです。View の部分だけ Vue.js という形になるんでしょうか。
